### PR TITLE
Read folderfiles

### PR DESCRIPTION
**Pull request by dave-frazzetto**
This PR resolves #(put issue number here).

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from <your_username>:master, but rather from <your_username>:<branch_name>.
2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ ] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - pycodestyle checkin
    - running the test suite
    - docs build

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# PR Description

Please describe the changes proposed in the pull request:

- 
- 
- 

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by HectorM14** [comment]
@dave-frazzetto  @ericmjl I was looking through the functions and saw `read_csvs()` and had a question about its usage. Is its intended usage is to supply a path to a file: `"path/to/file.csv"` or a path to a folder containing `.csv`s with or without wildcards: `"path/to/folder/"`, `"path/to/file*.csv"`.

Is that right? Would there also be usage where a list of paths is passed, and creates a combined dataframe?

**Comment by ericmjl** [comment]
@HectorM14 yes, you are correct - we pass a directory path into `read_csvs`, and then it automagically reads all CSVs inside that directory as a single DataFrame.

 > Would there also be usage where a list of paths is passed, and creates a combined dataframe?

This I think isn't implemented here, but would definitely be within scope for a PR!

**Comment by HectorM14** [comment]
Okay, got it. I think that's a PR I could do in the near future (unless anyone else does it first). 

In the meantime, does it make sense to move its tests to an `io` folder? It would just be the single file at the moment, but it would follow the structure of the other tests.

**Comment by ericmjl** [comment]
> does it make sense to move its tests to an io folder? It would just be the single file at the moment, but it would follow the structure of the other tests.

It can work both ways! I would also definitely accept a PR to move it into an `io/` directory if you did it, but no pressure here :smile".

**Pull request merged**
