### PR TITLE
[TST] Import `pandas` test functions in uniform pattern

### LINKED ISSUE #674: [TST] Use pandas.testing for compatibility
# Brief Description

`test_expand_grid.py` imports from `pandas._testing`, which is a more recent module in `pandas`, and doesn't exist in previous versions of `pandas`. Instead, other tests have imported from `pandas.testing` which still exists in newer versions of `pandas`. This is only an issue if we're keeping `pyjanitor`'s `pandas` compatibility at > 0.24, which means that we should also test/develop with that version as well.

https://github.com/ericmjl/pyjanitor/blob/62ee72fc5ed2fe6d80acc6663d222458252c03de/tests/functions/test_expand_grid.py#L6

This fix is a simple one, and could be combined with #675

### PR DESCRIPTION
**Pull request by hectormz**
# PR Description

Please describe the changes proposed in the pull request:

- This imports `assert_frame_equal` directly from `pandas.testing` instead of using `pd.testing.assert_frame_equal`
- Also changes imports from private `pandas._testing` to `pandas.testing`

**This PR resolves #674.**

# PR Checklist

Please ensure that you have done the following:

1. [X] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [X] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [X] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [X] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
@hectormz in case it helps, I pasted here the errors from Azure. They all pertain to Flake8 only.

```
./tests/spark/functions/test_update_where_spark.py:1:1: F401 'pandas as pd' imported but unused
./tests/spark/functions/test_update_where_spark.py:18:5: F821 undefined name 'assert_frame_equal'
./tests/spark/functions/test_update_where_spark.py:41:5: F821 undefined name 'assert_frame_equal'
./tests/spark/functions/test_update_where_spark.py:64:5: F821 undefined name 'assert_frame_equal'
./tests/spark/functions/test_update_where_spark.py:87:5: F821 undefined name 'assert_frame_equal'
./tests/functions/test_add_column.py:6:1: F401 'pandas.testing.assert_frame_equal' imported but unused
./tests/functions/test_collapse_levels.py:1:1: F401 'pandas as pd' imported but unused
./tests/functions/test_add_columns.py:6:1: F401 'pandas.testing.assert_frame_equal' imported but unused
./tests/functions/test_select_columns.py:1:1: F401 'pandas as pd' imported but unused
```

**Comment by hectormz** [comment]
Thanks @ericmjl ! I'm not sure how I missed these issues when running `make check`. I also want to add something in the documentation as you mentioned in the issue.

**Comment by ericmjl** [comment]
Let's get one more pair of eyes on here. @szuckerman?

**Comment by samukweku** [comment]
Will there be a comment/guide somewhere in the docs, advising code contributors to import ``assert_frame_equal`` instead of ``pd.testing.assert_frame_equal``

**Comment by samukweku** [comment]
I will keep a note of this for future contributions, as a reminder to myself. All that is left is to include this change somewhere in the docs for contributors. Well done @hectormz

**Comment by hectormz** [comment]
Thanks @samukweku . I have not yet added this usage pattern to the docs. I thought I would make a quick and dirty addition to our docs, but have since gone down a rabbit hole:

1. Our guide on unit tests doesn't use `assert_frame_equal` etc, which would be helpful to demonstrate
2. Our current guide is very nicely done and I don't want to mangle it by stuffing in this item
3. I know we did some docs rearranging in the past, but I think it might be worthwhile to consider another round of it to make some material more accessible (which would definitely be another issue)

@ericmjl perhaps we could add another section to/like `2. How should the test look like?` that uses one of these `pandas` assert functions. Or find a test that uses both.

**Comment by hectormz** [comment]
@ericmjl sorry I've left this open for so long. For simplicity sake, what do you think about demonstrating writing unit tests with `test_add_column_scalar`, which uses `assert_series_equal`, and a normal `assert`:

```python
@pytest.mark.functions
@given(df=df_strategy())
def test_add_column_scalar(df):
    # column appears in DataFrame
    df = df.add_column("fortytwo", 42)
    assert "fortytwo" in df.columns

    # values are correct in dataframe for scalar
    series = pd.Series([42] * len(df))
    series.name = "fortytwo"
    assert_series_equal(df["fortytwo"], series)

    # scalar values are correct for strings
    # also, verify sanity check excludes strings, which have a length:
```

If we went this route, I would add a test docstring as part of the commit.

But curious if anyone things this test is better/worse for teaching tests

**Comment by ericmjl** [comment]
@hectormz looks like a not bad one for teaching the practice of testing, and providing a good starting point. Let's go with it!

**Comment by ericmjl** [comment]
@hectormz, I'd like to propose merging, as the PR has been open for quite a while. If you're cool with that, please ping back. We can do the docs piece in a separate PR, unless you're close to finishing -- in which case, let's sneak in that piece here :smile:.

Others who haven't been so involved in the code review can chime in - don't feel shy! :smile:

**Comment by hectormz** [comment]
Yes, sorry! I've been a bit distracted. Please merge and I'll add the documentation separately

**Comment by ericmjl** [comment]
OK, it's been a few days without movement here. I'm going to hit the merge button. Thanks @hectomz!

**Pull request merged**
