### PR TITLE
Update requirements.txt

### PR DESCRIPTION
**Pull request by HectorM14**
Testing failed since I didn't have `hypothesis` and `requests` in my environment. `hypothesis` version was taken from the `.yml` file. `chemistry.py` also fails since I don't have `rdkit`, but that seems too niche and difficult to install, so I assume it's okay for those tests to fail for the rest of us.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
> chemistry.py also fails since I don't have rdkit, but that seems too niche and difficult to install, so I assume it's okay for those tests to fail for the rest of us.

Totally agree, don't worry about those tests locally. They will pass on Travis, though.

------

Currently, Travis is failing because it's doing `pip install -e .` rather than `python setup.py develop`. Can you pull `dev` into your branch so that the Travis build script is correct?

By the end of this sprint at PyCon, we will be moving off Travis to Azure Pipelines, which are more user-friendly for multiple OSes.

**Comment by ericmjl** [comment]
Meanwhile, I wouldn't worry about the tests failing on this PR, so I will go ahead and merge.

**Comment by HectorM14** [comment]
Great. Should I have PR'd into `dev` instead of `master`?

When is the sprint? Should I hold off cleaning up naming until after? (Or try to get them in before?)

**Comment by ericmjl** [comment]
> Should I have PR'd into dev instead of master?

Yes, but don't worry about this particular PR ;). @szuckerman made the suggestion to move have a `dev` branch, and we've stuck with that ever since.

> When is the sprint? Should I hold off cleaning up naming until after? (Or try to get them in before?)

We can do it concurrently, don't worry! That's because everyone will be working on a different portion of the codebase. I will be marking issues as "taken", and you can take on this one.

**Comment by HectorM14** [comment]
Got it. I'll update and later merge into `dev`.
Thanks for the pointers. I'll keep working on naming.

**Pull request merged**
