### PR TITLE
[INF] Add test pattern config to deep source

### PR DESCRIPTION
**Pull request by ericmjl**
This is an infrastructural pull request, in response to an email from a DeepSource employee sent to me:

> I noticed you've reported some false-positives for BAN-B101 - Assert Statement used outside tests being raised for your test files.
> Right now, DeepSource identifies the test files with the help of the test-file glob you mention in `.deepsource.toml` config file.
> Since your config file is missing the `test_patterns` field, this issue is being raised for all of your files, including the test files.
> 
> To fix it, please update your `.deepsource.toml` config file with your test patterns.
> This [link](https://deepsource.io/docs/config/deepsource-toml.html#test-patterns) will take you to the required docs.

Tagging @zbarry and @samukweku, who are interested in infra-related stuff, as well as @hectormz, who has helped a ton with infrastructure before too.

### CODE REVIEW

**Comment by hectormz** [comment]
I haven't been paying close attention to the somewhat recent addition of DeepSource. Does that mean we can remove the flags added in this commit: https://github.com/ericmjl/pyjanitor/commit/a48ddab1e83c88fa640ab862767d92ef54dc19d7

**Comment by ericmjl** [comment]
@hectormz yes indeed, that's the case. Thanks for the catch!

**Comment by hectormz** [comment]
Hmm, still not happy. 

I have no idea how the `.toml` file is parsed, but maybe the `test_patterns = [...` is being gobbled by `[[analyzers]]` section. Maybe moving `test_patterns = [...` above `[[analyzers]]` will do the trick.

**Comment by ericmjl** [comment]
That's a good catch, @hectormz! Definitely one I wouldn't have caught. DeepSource is happy now :)

**Comment by ericmjl** [comment]
Okie dokes, @hectormz, please feel free to hit the "Squash and merge" button (even though it's not green!).

**Comment by hectormz** [comment]
Thanks @ericmjl !

**Pull request merged**
