### PR TITLE
Add min_max_scale

### PR DESCRIPTION
**Pull request by ericmjl**
# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from <your_username>:master, but rather from <your_username>:<branch_name>.
2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - pycodestyle checkin
    - running the test suite
    - docs build

## Code Changes

If you are adding code changes, please ensure the following:

- [x] Ensure that you have added tests.
- [x] Run all tests (`$ pytest .`) locally on your machine.
    - [x] Check to ensure that test coverage covers the lines of code that you have added.
    - [x] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [x] View the docs to check that it renders correctly.

# PR Description

Please describe the changes proposed in the pull request:

- Adds in a min_max_scale function that scales either a single column or a dataframe to the bounds of [0, 1]. 

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by zbarry** [comment]
Maybe make it scale to user-specifiable min/max? Formula for an array is:

`arr_new = (arr_old - arr_old.min()) * (new_max - new_min) / (arr_old.max() - arr_old.min()) + new_min`

(caching the min/max calculations of course)

https://en.wikipedia.org/wiki/Normalization_(image_processing)

**Comment by ericmjl** [comment]
Sounds like a good idea.

**Comment by zbarry** [comment]
Spelling error in commit message. Gotta scrap it.

**Comment by zbarry** [comment]
In docstring:

> If minimum and maximum are provided, then the data are linearly scaled to be between the two values. Otherwise, they are scaled to be between the minimum and maximum of the value.

Don't you mean if not provided, they are scaled from 0 to 1?

**Comment by ericmjl** [comment]
> Spelling error in commit message. Gotta scrap it.

No. 😛

>

> In docstring:
> 
> > If minimum and maximum are provided, then the data are linearly scaled to be between the two values. Otherwise, they are scaled to be between the minimum and maximum of the value.
> 
> Don't you mean if not provided, they are scaled from 0 to 1?

Good catch. Updating docstrings.

**Comment by zbarry** [comment]
sec

**Comment by zbarry** [comment]
https://gist.github.com/zbarry/f0e377b3c4aaea355d53df782c0ce89f

Suggested docstring.

I'd also consider `s/minimum/old_min`, `s/maximum/old_max`, `s/new_minimum/new_min` ...

**Comment by zbarry** [comment]
The isoelectric point example should probably be expounded on a bit as to what you mean exactly

**Comment by zbarry** [comment]
Would it make sense to raise an exception if max > min?

**Comment by zbarry** [comment]
What about the case where someone tries to min/max a `DataFrame` with some (or all) non-numerical columns?

It might actually be useful to gracefully handle detecting which things are numeric.

**Comment by zbarry** [comment]
Non-abbreviated minimum / maximums are still in dstring in the description part

**Comment by zbarry** [comment]
Either way, probably would want to include a test for an exception being raised if the user tries to min/max a particular column that's not numeric

**Comment by ericmjl** [comment]
Dood, you really could do with consolidating your comments into a single box dude. Makes things easier to track. Just edit your old comments. Stream-of-consciousness doesn't facilitate discussions, which is what the issue tracker and PR boards are intended for.

> The isoelectric point example should probably be expounded on a bit as to what you mean exactly.

Done.

> What about the case where someone tries to min/max a DataFrame with some (or all) non-numerical columns? It might actually be useful to gracefully handle detecting which things are numeric.

That should be for a later PR.

> Would it make sense to raise an exception if max > min?

Good idea.

**Comment by zbarry** [comment]
Lol whoops.

**Comment by ericmjl** [comment]
Ok, I'm ready to merge. We can make the function cover a broader use case later.

**Pull request merged**
