### PR TITLE
Fix environment-dev.yml

### PR DESCRIPTION
**Pull request by zbarry**
This PR resolves `environment-dev.yml` issues (not previously posted):

- JupyterLab should be a development dependency given we have example notebooks
- Python 3.6 was specifically getting pinned again (unintentional?)
- Known problem when RDKit is used on a system without X libraries being present:

https://sourceforge.net/p/rdkit/mailman/message/36341795/

This is relevant for people using Windows Subsystem for Linux.

> Hi,
>
>This looks like an error caused by the fact that the anaconda cairo builds
include a dependency on the system X libraries and you don't have X
installed.
>You can probably clear the problem up by installing the cairo build from
the RDKit channel. Run this inside the conda environment where you have the
RDKit installed:
>
>conda install -c rdkit nox
>conda install -c rdkit cairo
>
>-greg

Note that this was not sufficient for whatever reason; I had to install `xorg-libxrender` from `conda-forge`.

# Relevant Reviewers

- @ericmjl
- @szuckerman

### CODE REVIEW

**Comment by ericmjl** [comment]
Looks like it's only failing on the API request. @zbarry, can you comment out that test in this PR with a note, so that we can decide how better to test that in a later PR?

**Comment by zbarry** [comment]
@ericmjl - this has something to do with the CI system. All the tests pass locally. Maybe a workaround for now is a `skipif` in pytest that skips if it detects that the tests are being run via Travis?

https://docs.pytest.org/en/latest/skipping.html

**Comment by ericmjl** [comment]
> Maybe a workaround for now is a skipif in pytest that skips if it detects that the tests are being run via Travis?

Yes, that does sound like the best way forward for the time being. :smile: :+1:

**Comment by zbarry** [comment]
Do you know how to do such detection? I know nothing about our CI system.

**Comment by ericmjl** [comment]
Another idea: let's just mark this as xfail, so that if it passes, it's an xpass. 

https://docs.pytest.org/en/latest/skipping.html

**Pull request merged**
