### PR TITLE
[ENH][DOC] Upgrade to expand_grid function; example notebook included

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Example notebook for the expand_grid function included
- Speed improvement to the expand_grid function
-

**This PR is an update to  the expand_grid function**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [x] Ensure that you have added tests.
- [x] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by samukweku** [comment]
Not sure how to link to the expand_grid PR, so I did not attach a number.

**Comment by ericmjl** [comment]
@samukweku thanks for redoing the PR. I'm not sure why the code coverage has gone down even with a new PR in. I think we can safely ignore that piece.

The other thing that is happening is that the markdown files are being regenerated. The fact that they were in there to begin with was my fault, as I was a little inexperienced with that when the first commit happened. Can you remove the auto-generated markdown files and push? We'll consider it a clean slate from this point going forward. (Sorry for burdening you with the administrative tasks here - it should get better once we make this change.)

**Comment by samukweku** [comment]
Hi @ericmjl ; not a problem. Which markdown files are you referring to? could you point me to the specific folder(s)?

**Comment by ericmjl** [comment]
Indeed! It's the ones that are in: `docs/reference/janitor.functions/` and related directories. Basically the ones that are autogenerated. On the "changes" tab of the PR page, you'll notice they all look like this:

image

i.e. they have a line deleted and then added back that is identical.

**Comment by samukweku** [comment]
not sure if i broke something, so i'll close this and run another pull request

**Pull request closed without merging**
