### PR TITLE
[DOC] Update teacher pupil notebook #414

### LINKED ISSUE #414: [DOC] Add more description of why the teacher_pupil data needs to be cleaned.
# Brief Description

I'd like to add more description in the beginning of the notebook on why the indicator column needs to be cleaned, and motivate the creation of the functions.

(optional but encouraged) This notebook would likely cover the following pyjanitor functions:

# Dataset

https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-05-07/EDULIT_DS_06052019101747206.csv

### PR DESCRIPTION
**Pull request by portc13**
# PR Description

Please describe the changes proposed in the pull request: 

- updated the documentation on the teach pupil notebook
- motivate the custom functions created in the example for string 

**This PR resolves #414 

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:master, but rather from `<your_username>`:<branch_name>.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - pycodestyle checking
    - running the test suite
    - docs build
    
Once done, please check off the check-box above.
    
If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [x] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by portc13** [comment]
yes, I've added myself to the AUTHORS.rst

**Comment by ericmjl** [comment]
Thanks, @portc13. There‘s a large conflict that I think can be resolved by having you update the branch from origin/dev. Do you know the bash commands to make this happen? If not, let me know, we can get the instructions into your hands.

**Comment by portc13** [comment]
The conflict was me adding myself to AUTHOR.rst. I don't know the commands to resolve this conflict. If you can share them here I work on fixing the conflict. Thanks

**Comment by ericmjl** [comment]
Ok, not a problem!

First off, you will want to pull in changes from `dev`:

```bash
# Ensure that you are on your branch.
# Then, run:
$ git fetch upstream # this assumes that you have a remote called “upstream” that points to ericmjl/pyjanitor. If not, you will need to add this remote.
$ git merge upstream/master
$ git push
```

**Comment by portc13** [comment]
Thanks Eric. I think I've fixed the conflict

**Pull request merged**
