### PR TITLE
[DOC] Updated general_functions API page

### LINKED ISSUE #678: Some functions not showing on the API documentation page
Noticed that some functions are missing from the API documentation page. ```unionize_dataframe_categories``` and ```move``` functions are not listed on the API docs page. Not sure which other ones are missing. Not sure how this can be fixed; if anyone can point me on how to fix it (if I can), that would be great.

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Added functions to the general_functions API page
-
-

**This PR resolves #678 .**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [x] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl
- @hectormz

### CODE REVIEW

**Comment by hectormz** [comment]
Thanks @samukweku. Was this a manual process to compare lists of functions and see what was missing?

Don't forget to list what you did in the changelog! I almost always start the PR and realize I forgot to update the changelog

**Comment by samukweku** [comment]
I did a check using ``Ipython``, comparing stripped filenames from the ``functions`` subfolder in ``tests``, with function names already included in ``docs/reference/general_functions.rst`` to get the missing functions. 

Thanks @hectormz, I will include it in the changelog.

**Comment by ericmjl** [comment]
Thanks @samukweku! Does what you did in IPython look like it could be written as a script? If so, could you paste it in an issue? I'll probably do a PR that adds some automated checks, which I think will be super helpful for maintaining docs quality.

**Comment by samukweku** [comment]
sure @ericmjl !, I will create a script and share in an issue.

**Comment by samukweku** [comment]
Hi @ericmjl and @HectorM14; if it is ok with you, kindly have one more check on this ``PR``, and if it is ok, a merge would be great.   Unless it is ok for me to go ahead and do that; I wonder if it is safe or proper for me to do so. Thanks!

**Comment by ericmjl** [comment]
Thanks for the ping-in, @samukweku! OK, I'm going to merge now. Wonderful work :smile:.

**Pull request merged**
