### PR TITLE
[DOC] Added clarificafying admonitions to Get Started for Windows use…

### LINKED ISSUE #532: Clarifications to 'Get Started!' section of documentation, based on errors encountered
## Clarifications to the `Get Started!` section of contributing.html

All: It took me a surprisingly long time to get the `pyjanitor` development environment set up on Windows 10. I have a couple of questions and an offer to add some clarifications

## Relevant Context

- [Contributing.html](https://pyjanitor.readthedocs.io/contributing.html)
- What follows refers to the [Get Started!](https://pyjanitor.readthedocs.io/contributing.html#get-started) section
### 1. Running make on Windows
I got stuck while trying to run make. The documentation is helpful and instructed me to run:

     $ conda install -c defaults -c conda-forge make

This worked fine. However, even though `make` was installed, I got the 'bash: make not found' error. 

*Question:* How to follow up after conda installing make? Do I need to add it explicitly to $PATH? The documentation does not explain this part.

After a lot of searching, I found one fix that let me proceed. It had to do copying with MinGW, 
which has a `make` in one of the bin directories. (I can add a note in docs to this for other Windows developers who will follow. Not sure how typical this is.)

Finally, got `make install` to work fine.

### 2. Running `make docs`

Next, I was hit with an error saying modules were not found. (But `make install` had worked fine.) I was following the instructions verbatim, but there was no mention of activating the conda environment.

Once I ran `source activate pyjanitor-dev` things worked fine when I *then* ran `make docs`

If my understanding is correct, source activate is needed prior to running `make docs` 

Based on my experience, I'd like to make a few very minor modifications to the 'Getting Started' section of the documentation to make it easier for future developers of pyjanitor.

Please let me know if this is something that would be relevant. Also, I am not sure if my understanding of the steps is correct.

Or perhaps my experience was not typical, in which case we shouldn't modify the Getting Started instructions.

### PR DESCRIPTION
**Pull request by Ram-N**
…rs #532

# PR Description

Please describe the changes proposed in the pull request: 

- Added two small admonitions in the Getting Started! section of CONTRIBUTING.rst
- Both are targeted at Developers on Windows platform
- They have to do with installing `make` and activating the dev environment
- Had to add the line in `expected = expected.astype({"null_flag": "int32"})` in `tests/functions/test_flag_nulls.py` per #501 discussion

**This PR resolves #532 .**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:master, but rather from `<your_username>`:<branch_name>.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - pycodestyle checking
    - running the test suite
    - docs build
    
Once done, please check off the check-box above.
    
If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [x] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl
- @jk3587 
- @anzelpwj

### CODE REVIEW

**Comment by anzelpwj** [comment]
Thanks for taking care of the `null_flag` issue - I hadn't had the chance to get to it (just busy with family things).

**Comment by anzelpwj** [comment]
LOL, it looks like for Mac and Linux machines we have the opposite problem. What a mess...

**Comment by anzelpwj** [comment]
```python
if sys.platform.startswith('win32'):
    expected = expected.astype({"flag": "int32"})
```

**Comment by Ram-N** [comment]
Thanks, @anzelpwj 
I wish I didn't have to add that, but I will and re-submit a PR.

Any reason you went with `sys.platform.startswith('win32'):` instead of `sys.platform == 'win32':` ?

**Comment by anzelpwj** [comment]
Yeah, it's horribly hacky.

Mostly just copied what was in the Python docs. `== 'win32'` should be equally valid.

**Comment by anzelpwj** [comment]
Wait, never mind. We need to set `check_dtype=False` in `assert_frame_equal`. For some reason I thought it was `check_column_type` and we were getting errors. We can skip all the stuff with `sys.platform`.

**Comment by Ram-N** [comment]
@anzelpwj now you are talking! Thank you for this tip. Let me try setting `check_dtype=False`

**Comment by ericmjl** [comment]
@Ram-N, thank you for the contribution, and thanks to you too, @anzelpwj for chiming in here!

Before I merge, @Ram-N, and I confirm that the docs render correctly on your computer? Just need to give me a yes/no, I’m happy to trust your response and run with it.

**Comment by Ram-N** [comment]
@ericmjl Yes, I can confirm that the docs rendered correctly on my computer. I've made the changes you requested. Thanks.

**Comment by ericmjl** [comment]
Woohoo! Thanks a lot, @Ram-N!

**Pull request merged**
