### PR TITLE
[DOC] Update missing docstring parameters

### PR DESCRIPTION
**Pull request by HectorM14**
# PR Description

Please describe the changes proposed in the pull request: 

- Added/corrected parameters missing from some docstrings
- Corrected reference in `_clean_accounting_column` docstring to argument `type`, which is now `cleaning_style`

# PR Checklist

Please ensure that you have done the following:

1. [X] PR in from a fork off your branch. Do not PR from `<your_username>`:master, but rather from `<your_username>`:<branch_name>.

2. [X] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ ] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - [X] black formatting
    - [X] pycodestyle checking
    - running the test suite
    - docs build
    
Once done, please check off the check-box above.
    
If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
Everything passes and looks great. Thanks @HectorM14!

**Comment by zbarry** [comment]
@ericmjl / @HectorM14 - didn't see this in time, but `col` should be changed to `column` to account for the new naming consistency change, right?

**Comment by HectorM14** [comment]
@zbarry  Are you referring to `mols_col` ? I didn't change its name during the this commit since I was just checking docstrings. But following the pattern I've used so far, I suppose I'd change it to `mols_column_name`. Does that seem right? (Mostly) Everywhere else we now have something along the lines of `column_name`

**Comment by zbarry** [comment]
Oh yeah, whoops, `column_name`. And ok, I'll add it to my refactoring PR so don't worry about it. Thanks!

**Comment by HectorM14** [comment]
Great @zbarry !

**Pull request merged**
