### PR TITLE
Bin numeric

### PR DESCRIPTION
**Pull request by jcvall**
This PR resolves #(put issue number here).

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from <your_username>:master, but rather from <your_username>:<branch_name>.
2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ ] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - pycodestyle checkin
    - running the test suite
    - docs build

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# PR Description

Please describe the changes proposed in the pull request:

- 
- 
- 

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
@jcvall thanks for this PR! 

PyCon 2019 sprints start on Monday - I will be focusing on pyjanitor development there! Do give me a day or so to get myself oriented; it's the first time I'm leading a sprint, super excited!

**Comment by jcvall** [comment]
Yes.  I will fix.  

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by jcvall** [comment]
I figuring out how to install the black jupyterlab extension on my computer for the future. So I can just format the code as I am writing.  Some how when I run black from the terminal it is not updating the file like it says it is.

**Comment by jcvall** [comment]
Should I fix the test_bin_numeric.py file too?

**Comment by ericmjl** [comment]
> I'm figuring out how to install the black jupyterlab extension on my computer for the future. So I can just format the code as I am writing. 

Cool, do let me know how that goes, @jcvall! 

> Some how when I run black from the terminal it is not updating the file like it says it is.

The current best guess that I can make is that you're running black not from the project directory, i.e. from `{/path/to}/pyjanitor` (<- this is the top-level project directory), perhaps? i.e. you shouldn't be in `{/path/to}/pyjanitor/janitor`, but one level up from there. The `make black` command should do the trick for you once you're in the top-level project directory.

**Comment by zbarry** [comment]
@jcvall - just as an aside, a lot of what Black is doing is formatting code according to the Python style guide set out in PEP 8, if you want to read some docs: https://www.python.org/dev/peps/pep-0008/

Also, PyCharm (Community Edition) has linters built in to yell at you when certain styling aspects are violated. I find it pretty helpful.

**Comment by jcvall** [comment]
I finally got the black extension to work with jupyterlab.  I will defiantly check out the PEP * style guide.  Thanks @zbarry

**Comment by jcvall** [comment]
I see I pulled in a lot of code I shouldn't have.  I will resubmit next week.  I know things will be busy.

**Comment by ericmjl** [comment]
I think this was resolved by @kurtispinkney in #272!

**Pull request closed without merging**
