### PR TITLE
[TST] Fix expand_grid test on Windows

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- This is a test update in reference to #675 
-

**This PR refers to #675.**

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ ] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @hectormz

### CODE REVIEW

**Comment by hectormz** [comment]
Thanks for putting this together @samukweku . I would suggest updating the PR title to something like `[TST] Fix expand_grid test on Windows` when others look at it for future reference.

I'm also wondering if @ericmjl has any thoughts on just making a new line/entry for each PR instead of wrapping your recent contributions into one big contributions. Take credit for your many separate efforts!

**Comment by hectormz** [comment]
In that case @samukweku , I would add
```
[TST] Updated test_expand_grid to account for int dtype difference in Windows OS @samukweku
```
To the bottom of the top section of the changelog. In the proposed changes you currently have, there is a duplicated line. So I would remove those proposed changes, and just add what I have put here to keep it all organized

**Comment by samukweku** [comment]
@hectormz  Thanks for the suggestions; I will apply the changes.

**Comment by hectormz** [comment]
Hi @samukweku I just adjust the changelog a bit further. You can see the final version, and follow that pattern. I'll wait for the CI to finish, but this will be good to merge. thanks!

**Pull request merged**
