### PR TITLE
[ENH] Mega-refactoring

### PR DESCRIPTION
**Pull request by zbarry**
Added and revised type hinting, addressed variable naming issues, inserted subtle bugs, etc.

Also resolves: #339 

@ericmjl

### CODE REVIEW

**Comment by HectorM14** [comment]
@zbarry Nice use of a decorator 😉

**Comment by ericmjl** [comment]
Looks like it's only pycodestyle issues.

A single dose of `black` should solve the issue.

**Comment by ericmjl** [comment]
(The bottom of [this page](https://github.com/ericmjl/pyjanitor/pull/349/checks?check_run_id=125292634) should give you a link to view the build details.)

**Comment by HectorM14** [comment]
@ericmjl @zbarry Looks like lines of the docstrings are too long, which `black` doesn't fix (for me at least)

**Comment by zbarry** [comment]
Yep. It just made it onto black's to do list: https://github.com/python/black/issues/144 / https://github.com/python/black/projects/3#card-21181711

**Comment by ericmjl** [comment]
I like how auto doc formatting is an "AST-unsafe change". That said, anything that reduces friction for consistency is great!

**Pull request merged**
