### PR TITLE
Pyjanitor string functions

### LINKED ISSUE #360: [ENH] Wrap pandas string methods
# Brief Description

One thing that might be nice is to wrap all of the string methods such that they are now method-chainable.

If this could be done programmatically, that would be awesome. Otherwise, manually wrapping ones of interest, and building up a submodule of string method operations, would be a superb alternative.

# Example API

The example API can be found in [this notebook](https://github.com/ericmjl/pyjanitor/blob/dev/examples/notebooks/tidytuesday_20190423.ipynb).

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

- Wrapper for Pandas' string methods

**This PR resolves #360 .**

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ ] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by samukweku** [comment]
This is just a subset of the functions. Love your feedback on it before proceeding further.

**Comment by samukweku** [comment]
@ericmjl @zbarry @szuckerman @hectormz If you have some time, could you please have a look at this; would love to get you feedback on this format before I proceed further.

**Comment by hectormz** [comment]
@samukweku  starting to look at this now.

Are you rebasing from the most recent `dev` branch`? I'm seeing commits in this PR that should already have been added to the `dev` branch from previous PRs

**Comment by samukweku** [comment]
Hi @hectormz; thanks for having a look; the same commits showed up in the test_grid PR; I will have a look again and if all else fails, I will push a new PR altogether. What's your take on the class method for the string names. Have you got better suggestions? Your experience here will be helpful. Thanks.

**Pull request closed without merging**
