### PR TITLE
[ENH] Removing in-place from Add_column function

### LINKED ISSUE #214: [BUG] Add_column should not add the column in place
As suggested by Eric, Add-column should no longer change the data frame in-place. I would like to work on that.

### PR DESCRIPTION
**Pull request by Rajat-181**
This PR resolves #214 .

# PR Checklist

Please ensure that you have done the following:

1. [ ] PR in from a fork off your branch. Do not PR from <your_username>:master, but rather from <your_username>:<branch_name>.
2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ ] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - pycodestyle checkin
    - running the test suite
    - docs build

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# PR Description

Please describe the changes proposed in the pull request:

- 
- 
- 

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
@Rajat-181, I just resolved a conflict in AUTHORS.rst. Please run `git pull` so that the latest changes in your remote (`Rajat-181:updateexample`) get reflected in your local branch.

**Comment by Rajat-181** [comment]
Yes, I would work on that

**Comment by ericmjl** [comment]
@Rajat-181, it looks like the build is failing on code style checking.

```
./janitor/functions.py:1354:19: E261 at least two spaces before inline comment
./janitor/functions.py:1354:20: E262 inline comment should start with '# '
./tests/functions/test_add_column.py:117:1: E302 expected 2 blank lines, found 1
```

Could you fix the above three lines?

**Comment by ericmjl** [comment]
Also, I just resolved the AUTHORS.rst conflict on Github. Don't forget to `git pull` in your feature branch!

**Comment by ericmjl** [comment]
This one appears to be a duplicate of #279. I am going to close this. Please feel free to reopen if I'm incorrect.

**Pull request closed without merging**
