### PR TITLE
updated contributing w.r.t. a proposal to introduce a dev-master merge split

### PR DESCRIPTION
**Pull request by zbarry**
First draft addressing proposal in #118. 

@ericmjl @szuckerman

### CODE REVIEW

**Comment by ericmjl** [comment]
LGTM! @szuckerman, if you're good with the documentation, then feel free to press the big green button!

**Comment by zbarry** [comment]
Once merged, we're gonna want to just create `dev` and push it.

**Comment by zbarry** [comment]
image

Strange error with python 3.5 / python 3.7 references in the same log.

**Comment by ericmjl** [comment]
I think a simple restart of the job should do the trick. Do you guys have the necessary access privileges to do so?

**Comment by zbarry** [comment]
> I think a simple restart of the job should do the trick. Do you guys have the necessary access privileges to do so?

No idea how I'd even check

**Pull request merged**
