### PR TITLE
[INF] Require pandas >= 1.0.0

### PR DESCRIPTION
**Pull request by hectormz**
# PR Description

Please describe the changes proposed in the pull request:

- Updates minimum `pandas` version from 0.24 to 1.0.0

**This PR does not directly resolve an issue, but arose from conversation with @ericmjl.**

**Our CI uses the latest version of `pandas`, and this simplifies (likely) future compatibility issues.**

As some background, this initially arose because we have some tests that import from `pandas._testing`, which doesn't exist <1.0. I think we should import from `pandas.testing` anyway, so the `pandas` version becomes less of an issue. However, if we're claiming to be `pandas>=0.24` compatible, we might want to consider adding a CI job that will test on `pandas==0.24` in addition to `pandas==latest`.

# PR Checklist

Please ensure that you have done the following:

1. [X] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [X] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [X] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [X] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl
- @zbarry 
- @szuckerman

### CODE REVIEW

**Comment by hectormz** [comment]
Not sure about the "10 fewer hit lines", but this seems to match what happened in #673

**Comment by ericmjl** [comment]
> Not sure about the "10 fewer hit lines", but this seems to match what happened in #673

Yeah, not worried about this one! :smile: I approve!

**Comment by ericmjl** [comment]
As a matter of habit, let's get one more eye on PRs, so that there's a culture of 2 or more reviews per PR. @anzelpwj, reviewing this PR should fit your schedule, I think, as it's of a very narrow scope. Would you like to do the honors?

**Comment by szuckerman** [comment]
I’m just seeing this now, and take my comment with a grain of salt since I haven’t been contributing much to the project recently, but I’m not sure it’s the best thing to require the most recent version of a library. 

There are some users who might not be able to upgrade as often as you’d think and this might make the library inaccessible to them. 

But, narrowing in on a version does make it easier for development and if the majority of users will just “pip install” the latest version of pyjanitor anyway, this might not be a big deal. Just a few thoughts.

**Comment by hectormz** [comment]
Hi @szuckerman that's a valid point. We weren't really sure where the `pyjanitor` contributors and users stood regarding `pandas` requirements. 

As some background, this initially arose because we have some tests that import from `pandas._testing`, which doesn't exist <1.0. I think we should import from `pandas.testing` anyway, so the `pandas` version becomes less of an issue. However, if we're claiming to be `pandas>=0.24` compatible, we might want to consider adding a CI job that will test on `pandas==0.24` in addition to `pandas==latest`.

I'll update the original PR comment with this info.

**Comment by ericmjl** [comment]
> There are some users who might not be able to upgrade as often as you’d think and this might make the library inaccessible to them.

That is true, and I agree with you. 

> But, narrowing in on a version does make it easier for development and if the majority of users will just “pip install” the latest version of pyjanitor anyway, this might not be a big deal. Just a few thoughts.

This is also true. 

On balance, taking into account the fact that pandas 1.x has been pretty backwards-compliant with the old 0.2x APIs, I think it's okay to pin to 1.0, which is a pretty early version.

**Comment by ericmjl** [comment]
I don't want this one to hang too long, so I'm going to merge.

**Pull request merged**
