### PR TITLE
[ENH] #617 expand_grid function

### LINKED ISSUE #617: [ENH] add an expand_grid function
Recently watched a video by David Robinson on tidytuesday where he used the crossing function (a wrapper of the base r function expand_grid) from tidyr R library to do a Monte Carlo simulation.  I think this would a great addition to pyjanitor.  Don’t have the bandwidth at the moment to add it, but could in the near future.  I did come across a stackoverflow solution to this 

https://stackoverflow.com/questions/12130883/r-expand-grid-function-in-python

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

### PR DESCRIPTION
**Pull request by samukweku**
# PR Description

Please describe the changes proposed in the pull request:

-expand_grid function for combination of all inputs
-inputs have to be name value pairs - a dictionary
-

**This PR resolves #617 .**

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [x] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [x] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [x] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
@samukweku thank you for your PR! I appreciate the effort put in.

One thing that is slowing me down on the review is the number of files that have been changed relative to the `dev` branch. Have you pulled in the latest changes from `dev`? If not, would you be open to restarting the PR from a slightly cleaner state?

This is what I'd propose:

- Firstly, back up all of your _relevant_ changes by copying and pasting the files you intended to change into a separate directory.
- Then delete your local clone and your fork of pyjanitor
- Then fork pyjanitor once again.

Doing this ensures that you have the latest version of pyjanitor from which you make a new PR. (I'm not sure if you've been doing this already, so if you have, please treat all of the above as me just blabbering!)

At this point, there's a few ways you can go on.

### Use dev containers

I recently got up "dev containers" going, and they are available on the latest `dev` (which means your new fork will have them!) If you use VSCode and have the entire VSCode Remote extension suite installed, you can do "Open Repository in Container" (or something similar to that), and then type in `samukweku/pyjanitor`. This will get you in a completely isolated environment that has all of the dependencies already installed. 

If not, you can always clone your new fork locally.

The reason I set up dev containers is to simplify the development experience for new contributors. New contributors will only have to worry about deleting and re-forking the repositories, and won't have to worry about maintaining their fork (with git pulls from upstream and pushes to them).

OK, that was my long-winded blurb. **Would you be open to re-doing the PR?** I know you've probably put in a lot of effort, and I would love to be able to get `expand_grid` into the library soon, but I am also a bit crunched for time lately, so anything that helps me speed up the review (i.e. small diffs!) would be really helpful for doing a proper code review. Please let me know what you think.

**Comment by samukweku** [comment]
Thanks for the feedback! I'll follow the instructions.

**Comment by samukweku** [comment]
not sure how to link to this, so I created a new PR. would appreciate ur guidance on how to merge with this

**Comment by ericmjl** [comment]
Wonderful, thanks @samukweku! I'm going to close this PR in favour of #666 (that's how we link them :smile:)

**Pull request closed without merging**
