### PR TITLE
Case when()

### PR DESCRIPTION
**Pull request by jcvall**
This PR resolves #(put issue number here).

# PR Checklist

Please ensure that you have done the following:

1. [x] PR in from a fork off your branch. Do not PR from <your_username>:master, but rather from <your_username>:<branch_name>.
2. [x] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ ] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - pycodestyle checkin
    - running the test suite
    - docs build

## Code Changes

If you are adding code changes, please ensure the following:

- [x] Ensure that you have added tests.
- [x] Run all tests (`$ pytest .`) locally on your machine.
    - [x] Check to ensure that test coverage covers the lines of code that you have added.
    - [x] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# PR Description

Please describe the changes proposed in the pull request:

- 
- 
- 

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by jcvall** [comment]
I ran into some problems from the example I gave last afternoon.  After some research I come up with this.

**Comment by ericmjl** [comment]
@jcvall I think there may have been an issue with your commit history, resulting in many more lines of code being commited into here than what is correct. We recently switched to using the `dev` branch as the branch on which new PRs are merged into, and that I suspect may be part of the problem. 

@szuckerman can provide more thoughts on why it could be a better practice than PR-ing into `master` all the time. 

Would you be kind enough to redo the PR, this time by first:

- Copy/pasting your changes into some other text file in a temporary place on your hard drive.
- Deleting your local copy of pyjanitor
- Deleting your fork of pyjanitor
- Re-forking pyjanitor
- Re-cloning your fork of pyjanitor locally
- And finally, creating a new local branch from `dev` (and not `master`)? 

Once you've done that, you can paste back in the changes. That should also resolve the merge conflict. (Those pointers above are also how one "nukes" their own fork/local copy of a repository, if anything goes wrong. And don't worry about this being a newcomer programmer-only problem - experienced devs do this all the time too!)

**Comment by jcvall** [comment]
So sorry that it happened.  I will try again tonight.  Hopefully with better results.

**Comment by ericmjl** [comment]
@jcvall no need to be sorry! These sorts of things happen, and are a normal part of software development.

Take your time, I do appreciate your contribution; everything else about the PR looks great, and with a cleaner PR, myself or @szuckerman or @zbarry can handle a more in-depth review more easily.

**Pull request closed without merging**
