### PR TITLE
[DOC] Pep8 the notebooks and markdown files in  examples #415

### LINKED ISSUE #415: [DOC] pep8 style fix for code examples
# Brief Description of Fix

Right now, some of the code examples don't fit the python style guide.  I'd like to change them to match, ideally automatically with flake8 but for now just manually.

# Relevant Context
At [the board game example]( http://localhost:63342/pyjanitor/docs/_build/html/notebooks/board_games.html#Check-to-see-what-percentage-of-the-values-in-the-%E2%80%9Ccompilation%E2%80%9D-column-are-not-null)

Before:
```python
len(df[df['compilation'].notnull()])/len(df)
```

After:
```python
len(df[df['compilation'].notnull()]) / len(df)
```

- [Link to documentation page](http://pyjanitor.readthedocs.io)
- [Link to exact file to be edited](https://github.com/ericmjl/pyjanitor/AUTHORS.rst)

### PR DESCRIPTION
**Pull request by VPerrollaz**
# PR Description

Please describe the changes proposed in the pull request:

- Pep8 the examples notebooks and the code blocks in the markdown files of examples
- When in doubt I used black for inspiration

**This PR resolves #415 .**

# PR Checklist

Please ensure that you have done the following:

1. [ x] PR in from a fork off your branch. Do not PR from `<your_username>`:`dev`, but rather from `<your_username>`:`<feature-branch_name>`.

2. [ ] If you're not on the contributors list, add yourself to `AUTHORS.rst`.

3. [ ] Add a line to `CHANGELOG.rst` under the latest version header (i.e. the one that is "on deck") describing the contribution.
    - Do use some discretion here; if there are multiple PRs that are related, keep them in a single line.

## Quick Check

To do a very quick check that everything is correct, follow these steps below:

- [ x] Run the command `make check` from pyjanitor's top-level directory. This will automatically run:
    - black formatting
    - flake8 checking
    - running the test suite
    - docs build

Once done, please check off the check-box above.

If `make check` does not work for you, you can execute the commands listed in the Makefile individually.

## Code Changes

If you are adding code changes, please ensure the following:

- [ ] Ensure that you have added tests.
- [ ] Run all tests (`$ pytest .`) locally on your machine.
    - [ ] Check to ensure that test coverage covers the lines of code that you have added.
    - [ ] Ensure that all tests pass.

## Documentation Changes

If you are adding documentation changes, please ensure the following:

- [ ] Build the docs locally.
- [ ] View the docs to check that it renders correctly.

# Relevant Reviewers

Please tag maintainers to review.

- @ericmjl

### CODE REVIEW

**Comment by ericmjl** [comment]
@VPerrollaz thank you for your PR! I appreciate that you've taken the time to curate the changes.

It appears that the PR is failing on something that I have fixed in #653. Hang tight while I fix up those changes. Once they're in, I'll ping you here and have you update your branch with the latest version of `dev`, which should then fix up the whole thing.

**Comment by ericmjl** [comment]
@VPerrollaz the other PR is merged! Would you be kind enough to update your branch with the latest commit from `dev`? 

Let me know here if you have any issues.

**Comment by VPerrollaz** [comment]
Hello,
let me know if this is what you needed.

**Comment by ericmjl** [comment]
Thanks @VPerrollaz! :smile:

It appears the build is failing on something that should have been fixed in the previous PRs, but wasn't. Might be because of the changes made to the notebooks in this PR, which would take precedence over the previous fixes that I had introduced. Specifically, I see the following error:

```
CellExecutionError in notebooks/normalize.ipynb:
------------------
cars_df.transform_column(
    ['mpg', 'disp_cc', 'hp'],
    lambda x: (x-x.mean()) / x.std()
)
------------------
```

This one is a simple fix. Can you go to `notebooks/normalize.ipynb`, and change the `transform_column` to `transform_columns`? Also please check that there's no other similar ones to fix?

Finally, I realized you haven't added to the changelog and added yourself to the contributors list. Please do so! I want to make sure your contributions are recognized and recorded.

Once that is done, we'll look out for any more build errors. Once the build passes, we'll be golden, and can merge!

**Comment by VPerrollaz** [comment]
Ok I realized that I tested the notebooks with my system version of janitor which is why everything looked fine to me :(

In the above case changing from transform_column to transform_columns was not sufficient I had to add the option elementwise=False.
Do we have to change the explanation above the cell?
I will check every other notebook again and let you know once it is done.

**Comment by ericmjl** [comment]
@VPerrollaz thanks for getting back! In response to your question:

> Do we have to change the explanation above the cell?

If you feel comfortable doing it, please do so! Otherwise, I'm okay leaving the explanation till a bit later, when we do a docs revamp that I have planned.

**Comment by VPerrollaz** [comment]
Ok this time it seems everything went well. I didn't change the explanation just added an s to columns.

**Comment by ericmjl** [comment]
Wonderful stuff, thank you very much, @VPerrollaz! :smile: Very happy for your contribution to come by :).

**Pull request merged**
